name: deploycvat Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        
      - name: Add repos 
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add nuclio https://nuclio.github.io/nuclio/charts
          helm repo add vector https://helm.vector.dev
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add traefik https://helm.traefik.io/traefik

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          packages_with_index: true
          charts_dir: charts
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"